export type Lang = "de" | "en";

export const DEFAULT_LANG: Lang = "de";

export function normalizeLang(value: string | null | undefined): Lang {
  return value === "en" ? "en" : "de";
}

const translations = {
  de: {
    booking: "Online-Reservierung",
    title: "Tisch reservieren",
    subtitle: "Wählen Sie Datum, Uhrzeit und Personenzahl. Verfügbare Zeiten werden live aus dem Reservierungssystem geladen.",
    bookingDetails: "Reservierungsdetails",
    date: "Datum",
    guests: "Personenzahl",
    guestSuffix: "Personen",
    seating: "Sitzplatzwunsch",
    any: "Beliebig verfügbar",
    indoor: "Innenbereich",
    terrace: "Terrasse",
    availableTimes: "Verfügbare Zeiten",
    availableTimesHint: "Hier werden nur echte verfügbare Zeiten angezeigt.",
    slots: "Zeitfenster",
    candidateTables: "Passende Tische",
    reservedTables: "Reservierte Tische",
    lunch: "Mittag",
    dinner: "Abend",
    loadingAvailability: "Live-Verfügbarkeit wird geladen...",
    yourDetails: "Ihre Daten",
    yourDetailsHint: "Geben Sie Ihre Kontaktdaten ein, um die Reservierung abzuschließen.",
    fullName: "Vollständiger Name",
    fullNamePlaceholder: "Ihr vollständiger Name",
    phone: "Telefonnummer",
    phonePlaceholder: "+383...",
    email: "E-Mail",
    emailPlaceholder: "name@example.com",
    note: "Besondere Anfrage optional",
    notePlaceholder: "Fensterplatz, Geburtstag, Allergiehinweis...",
    complete: "Reservierung abschließen",
    submitting: "Wird gesendet...",
    success: "Reservierung erfolgreich erstellt.",
    confirmation: "Bestätigungscode",
    selectedTime: "Gewählte Uhrzeit",
    time: "Uhrzeit",
    noSlots: "Für dieses Datum und diese Personenzahl sind keine Zeiten verfügbar.",
    noAvailability: "Für dieses Datum, dieses Zeitfenster und diese Personenzahl sind keine Tische verfügbar.",
    dailyLimitReached: "Das Online-Reservierungslimit für diesen Tag wurde erreicht.",
    genericAvailabilityError: "Die Verfügbarkeit konnte nicht geladen werden. Bitte versuchen Sie es erneut.",
    chooseTimeError: "Bitte wählen Sie zuerst eine verfügbare Uhrzeit.",
    nameRequired: "Bitte geben Sie Ihren Namen ein.",
    phoneRequired: "Bitte geben Sie Ihre Telefonnummer ein.",
    contextMissing: "Der Reservierungskontext fehlt.",
    submitFailed: "Die Reservierung konnte nicht abgeschlossen werden.",
    language: "Sprache",
    german: "DE",
    english: "EN"
  },
  en: {
    booking: "Online booking",
    title: "Reserve your table",
    subtitle: "Choose your date, time and party size. Available time slots are loaded from the live reservation engine.",
    bookingDetails: "Booking details",
    date: "Date",
    guests: "Party size",
    guestSuffix: "guests",
    seating: "Seating preference",
    any: "Any available",
    indoor: "Indoor",
    terrace: "Terrace",
    availableTimes: "Available times",
    availableTimesHint: "Only real available slots are shown here.",
    slots: "Slots",
    candidateTables: "Candidate tables",
    reservedTables: "Reserved tables",
    lunch: "Lunch",
    dinner: "Dinner",
    loadingAvailability: "Loading live availability...",
    yourDetails: "Your details",
    yourDetailsHint: "Enter your contact details to complete the reservation.",
    fullName: "Full name",
    fullNamePlaceholder: "Your full name",
    phone: "Phone number",
    phonePlaceholder: "+383...",
    email: "Email",
    emailPlaceholder: "name@example.com",
    note: "Special request optional",
    notePlaceholder: "Window seat, birthday, allergy note...",
    complete: "Complete reservation",
    submitting: "Submitting...",
    success: "Reservation created successfully.",
    confirmation: "Confirmation code",
    selectedTime: "Selected time",
    time: "Time",
    noSlots: "No available slots for this date and party size.",
    noAvailability: "No tables are available for this date, time range and party size.",
    dailyLimitReached: "Online booking limit has been reached for this day.",
    genericAvailabilityError: "Availability could not be loaded. Please try again.",
    chooseTimeError: "Please choose an available time first.",
    nameRequired: "Please enter your name.",
    phoneRequired: "Please enter your phone number.",
    contextMissing: "Booking widget context is missing.",
    submitFailed: "Reservation could not be completed.",
    language: "Language",
    german: "DE",
    english: "EN"
  }
} as const;

export function t(lang: Lang) {
  return translations[lang] || translations.de;
}
