export type Lang = "en" | "sq" | "de";

export const DEFAULT_LANG: Lang = "en";

export const translations = {
  en: {
    booking: "Online booking",
    title: "Reserve your table",
    subtitle:
      "Choose your date, time and party size. Available time slots are loaded from the live reservation engine.",
    bookingDetails: "Booking details",
    date: "Date",
    guests: "Party size",
    seating: "Seating preference",
    indoor: "Indoor",
    terrace: "Terrace",
    any: "Any available",
    availableTimes: "Available times",
    availableTimesHint: "Only real available slots are shown here.",
    slots: "Slots",
    candidateTables: "Candidate tables",
    reservedTables: "Reserved tables",
    yourDetails: "Your details",
    yourDetailsHint: "Enter your contact details to complete the reservation.",
    fullName: "Full name",
    fullNamePlaceholder: "Your full name",
    phone: "Phone number",
    phonePlaceholder: "+383...",
    email: "Email (optional)",
    emailPlaceholder: "name@example.com",
    note: "Special request (optional)",
    notePlaceholder: "Window seat, birthday, allergy note...",
    complete: "Complete reservation",
    submitting: "Submitting...",
    success: "Reservation created successfully",
    confirmation: "Confirmation code",
    selectedTime: "Selected time",
    time: "Time",
    noSlots: "No available slots for this date and party size.",
    noAvailability: "No tables are available for this date, time range and party size.",
    dailyLimitReached: "Online booking limit has been reached for this day.",
    genericAvailabilityError: "Availability could not be loaded. Please try again."
  },

  sq: {
    booking: "Rezervim online",
    title: "Rezervo tavolinën",
    subtitle:
      "Zgjedh datën, orën dhe numrin e personave. Orët e lira ngarkohen nga sistemi i rezervimeve.",
    bookingDetails: "Detajet e rezervimit",
    date: "Data",
    guests: "Numri i personave",
    seating: "Preferenca e uljes",
    indoor: "Brenda",
    terrace: "Terrasa",
    any: "Çfarëdo që është e lirë",
    availableTimes: "Orët e lira",
    availableTimesHint: "Këtu shfaqen vetëm oraret realisht të lira.",
    slots: "Orare",
    candidateTables: "Tavolina kandidate",
    reservedTables: "Tavolina të rezervuara",
    yourDetails: "Detajet tuaja",
    yourDetailsHint: "Shkruani të dhënat tuaja për ta përfunduar rezervimin.",
    fullName: "Emri i plotë",
    fullNamePlaceholder: "Emri juaj i plotë",
    phone: "Numri i telefonit",
    phonePlaceholder: "+383...",
    email: "Email (opsional)",
    emailPlaceholder: "name@example.com",
    note: "Kërkesë shtesë (opsionale)",
    notePlaceholder: "Pranë dritares, ditëlindje, alergji...",
    complete: "Përfundo rezervimin",
    submitting: "Duke dërguar...",
    success: "Rezervimi u krijua me sukses",
    confirmation: "Kodi i konfirmimit",
    selectedTime: "Ora e zgjedhur",
    time: "Ora",
    noSlots: "Nuk ka orare të lira për këtë datë dhe këtë numër personash.",
    noAvailability: "Nuk ka tavolina të lira për këtë datë, këtë interval kohe dhe këtë numër personash.",
    dailyLimitReached: "Limiti i rezervimeve online për këtë ditë është arritur.",
    genericAvailabilityError: "Disponueshmëria nuk mund të ngarkohet. Ju lutem provoni përsëri."
  },

  de: {
    booking: "Online-Reservierung",
    title: "Tisch reservieren",
    subtitle:
      "Wählen Sie Datum, Uhrzeit und Personenzahl. Die verfügbaren Zeiten werden live geladen.",
    bookingDetails: "Reservierungsdetails",
    date: "Datum",
    guests: "Personenzahl",
    seating: "Sitzplatzwunsch",
    indoor: "Innenbereich",
    terrace: "Terrasse",
    any: "Beliebig verfügbar",
    availableTimes: "Verfügbare Zeiten",
    availableTimesHint: "Hier werden nur echte verfügbare Zeiten angezeigt.",
    slots: "Zeitfenster",
    candidateTables: "Passende Tische",
    reservedTables: "Reservierte Tische",
    yourDetails: "Ihre Daten",
    yourDetailsHint: "Geben Sie Ihre Kontaktdaten ein, um die Reservierung abzuschließen.",
    fullName: "Vollständiger Name",
    fullNamePlaceholder: "Ihr vollständiger Name",
    phone: "Telefonnummer",
    phonePlaceholder: "+383...",
    email: "E-Mail (optional)",
    emailPlaceholder: "name@example.com",
    note: "Besondere Anfrage (optional)",
    notePlaceholder: "Fensterplatz, Geburtstag, Allergiehinweis...",
    complete: "Reservierung abschließen",
    submitting: "Wird gesendet...",
    success: "Reservierung erfolgreich erstellt",
    confirmation: "Bestätigungscode",
    selectedTime: "Gewählte Uhrzeit",
    time: "Uhrzeit",
    noSlots: "Für dieses Datum und diese Personenzahl sind keine Zeiten verfügbar.",
    noAvailability: "Für dieses Datum, dieses Zeitfenster und diese Personenzahl sind keine Tische verfügbar.",
    dailyLimitReached: "Das Online-Reservierungslimit für diesen Tag wurde erreicht.",
    genericAvailabilityError: "Die Verfügbarkeit konnte nicht geladen werden. Bitte versuchen Sie es erneut."
  }
};

export function t(lang: Lang) {
  return translations[lang];
}